package config

import (
	"fmt"
	"os"
	"sync"
	"time"

	"clashgo/internal/utils"

	"go.uber.org/zap"
	"gopkg.in/yaml.v3"
)

// Manager 全局配置管理器
// 负责 verge.yaml / clash.yaml / profiles.yaml / runtime 的读写与并发安全
type Manager struct {
	mu sync.RWMutex

	verge    *IVerge
	clash    IClashBase
	profiles *IProfiles
	runtime  *RuntimeConfig
}

var (
	globalManager *Manager
	managerOnce   sync.Once
)

// NewManager 初始化并返回配置管理器（同时从磁盘加载所有配置）
func NewManager() (*Manager, error) {
	m := &Manager{
		runtime: NewRuntimeConfig(),
	}

	if err := m.load(); err != nil {
		return nil, fmt.Errorf("config manager load: %w", err)
	}

	managerOnce.Do(func() {
		globalManager = m
	})

	return m, nil
}

// Global 返回全局配置管理器（必须在 NewManager 之后调用）
func Global() *Manager {
	if globalManager == nil {
		panic("config.Manager not initialized")
	}
	return globalManager
}

// load 从磁盘读取所有配置文件
func (m *Manager) load() error {
	dirs := utils.Dirs()
	log := utils.Log()

	// 1. 加载 verge.yaml
	verge, err := readYAML[IVerge](dirs.VergePath())
	if err != nil {
		log.Warn("Failed to load verge.yaml, using defaults", zap.Error(err))
		def := DefaultVerge()
		verge = &def
		// 写入默认值
		if werr := writeYAML(dirs.VergePath(), verge, "# ClashGo Config"); werr != nil {
			log.Warn("Failed to write default verge.yaml", zap.Error(werr))
		}
	}
	// 验证并修正 clash_core
	if err := m.validateClashCore(verge); err != nil {
		log.Warn("Failed to validate clash_core", zap.Error(err))
	}
	m.verge = verge

	// 2. 加载 clash.yaml（Mihomo 基础配置）
	clash, err := readYAMLMap(dirs.ClashPath())
	if err != nil {
		log.Warn("Failed to load clash.yaml, using defaults", zap.Error(err))
		clash = defaultClashBase()
		_ = writeYAML(dirs.ClashPath(), clash, "# Generated by ClashGo")
	}
	m.clash = clash

	// 3. 加载 profiles.yaml
	profiles, err := readYAML[IProfiles](dirs.ProfilesPath())
	if err != nil {
		log.Warn("Failed to load profiles.yaml, using empty", zap.Error(err))
		profiles = &IProfiles{Items: []*IProfile{}}
		_ = writeYAML(dirs.ProfilesPath(), profiles, "# ClashGo Profiles")
	}
	m.profiles = profiles

	log.Info("Config loaded",
		zap.String("core", verge.GetClashCore()),
		zap.Int("profiles", len(profiles.Items)),
	)

	return nil
}

// ─────────────────────────────────────────────────────────────────────────────
// Verge 配置操作
// ─────────────────────────────────────────────────────────────────────────────

// GetVerge 返回当前 IVerge 的副本（只读）
func (m *Manager) GetVerge() IVerge {
	m.mu.RLock()
	defer m.mu.RUnlock()
	if m.verge == nil {
		return DefaultVerge()
	}
	return *m.verge
}

// PatchVerge 将 patch 中非 nil 字段合并到当前配置并持久化
func (m *Manager) PatchVerge(patch IVerge) error {
	m.mu.Lock()
	defer m.mu.Unlock()

	applyVergePatch(m.verge, &patch)

	if err := writeYAML(utils.Dirs().VergePath(), m.verge, "# ClashGo Config"); err != nil {
		return fmt.Errorf("verge save: %w", err)
	}
	return nil
}

// ─────────────────────────────────────────────────────────────────────────────
// Clash 基础配置操作
// ─────────────────────────────────────────────────────────────────────────────

// GetClash 返回 Clash 基础配置副本
func (m *Manager) GetClash() IClashBase {
	m.mu.RLock()
	defer m.mu.RUnlock()
	clone := make(IClashBase, len(m.clash))
	for k, v := range m.clash {
		clone[k] = v
	}
	return clone
}

// PatchClash 合并补丁并保存
func (m *Manager) PatchClash(patch map[string]interface{}) error {
	m.mu.Lock()
	defer m.mu.Unlock()

	for k, v := range patch {
		m.clash[k] = v
	}

	if err := writeYAML(utils.Dirs().ClashPath(), m.clash, "# Generated by ClashGo"); err != nil {
		return fmt.Errorf("clash save: %w", err)
	}
	return nil
}

// DeleteClashKey 从 clash 基础配置中完全删除指定键（避免写入 null 覆盖 profile 配置）
func (m *Manager) DeleteClashKey(key string) error {
	m.mu.Lock()
	defer m.mu.Unlock()

	delete(m.clash, key)

	if err := writeYAML(utils.Dirs().ClashPath(), m.clash, "# Generated by ClashGo"); err != nil {
		return fmt.Errorf("clash save (delete key): %w", err)
	}
	return nil
}

// ─────────────────────────────────────────────────────────────────────────────
// Profiles 操作
// ─────────────────────────────────────────────────────────────────────────────

// GetProfiles 返回所有 profiles
func (m *Manager) GetProfiles() IProfiles {
	m.mu.RLock()
	defer m.mu.RUnlock()
	if m.profiles == nil {
		return IProfiles{}
	}
	return *m.profiles
}

// GetCurrentProfile 返回当前激活的 Profile
func (m *Manager) GetCurrentProfile() *IProfile {
	m.mu.RLock()
	defer m.mu.RUnlock()
	if m.profiles == nil || m.profiles.Current == nil {
		return nil
	}
	for _, p := range m.profiles.Items {
		if p.UID != nil && *p.UID == *m.profiles.Current {
			return p
		}
	}
	return nil
}

// AddProfile 添加新 Profile 并保存
func (m *Manager) AddProfile(p *IProfile) error {
	m.mu.Lock()
	defer m.mu.Unlock()

	now := time.Now()
	p.UpdatedAt = &now

	m.profiles.Items = append(m.profiles.Items, p)
	return m.saveProfiles()
}

// UpdateProfile 更新已有 Profile
func (m *Manager) UpdateProfile(uid string, patch *IProfile) error {
	m.mu.Lock()
	defer m.mu.Unlock()

	for _, p := range m.profiles.Items {
		if p.UID != nil && *p.UID == uid {
			applyProfilePatch(p, patch)
			now := time.Now()
			p.UpdatedAt = &now
			return m.saveProfiles()
		}
	}
	return fmt.Errorf("profile not found: %s", uid)
}

// DeleteProfile 删除 Profile
func (m *Manager) DeleteProfile(uid string) error {
	m.mu.Lock()
	defer m.mu.Unlock()

	items := m.profiles.Items[:0]
	found := false
	for _, p := range m.profiles.Items {
		if p.UID != nil && *p.UID == uid {
			found = true
			// 删除对应文件
			dirs := utils.Dirs()
			if p.File != nil {
				_ = os.Remove(dirs.ProfilesDir() + "/" + *p.File)
			}
			continue
		}
		items = append(items, p)
	}
	if !found {
		return fmt.Errorf("profile not found: %s", uid)
	}

	// 如果删除的是当前使用的 profile，清空 current
	if m.profiles.Current != nil && *m.profiles.Current == uid {
		m.profiles.Current = nil
	}
	m.profiles.Items = items
	return m.saveProfiles()
}

// SetCurrentProfile 设置当前激活的 Profile
func (m *Manager) SetCurrentProfile(uid string) error {
	m.mu.Lock()
	defer m.mu.Unlock()

	found := false
	for _, p := range m.profiles.Items {
		if p.UID != nil && *p.UID == uid {
			found = true
			break
		}
	}
	if !found {
		return fmt.Errorf("profile not found: %s", uid)
	}
	m.profiles.Current = &uid
	return m.saveProfiles()
}

func (m *Manager) saveProfiles() error {
	return writeYAML(utils.Dirs().ProfilesPath(), m.profiles, "# ClashGo Profiles")
}

// ReorderProfiles 替换整个 profiles 列表（拖拽排序后用）
func (m *Manager) ReorderProfiles(items []*IProfile) error {
	m.mu.Lock()
	defer m.mu.Unlock()
	m.profiles.Items = items
	return m.saveProfiles()
}

// ─────────────────────────────────────────────────────────────────────────────
// Runtime 配置操作
// ─────────────────────────────────────────────────────────────────────────────

// RuntimeSnapshot 运行时配置的只读快照（不含 mutex，可安全按值传递）
type RuntimeSnapshot struct {
	Config     IClashBase             `json:"config"`
	ExistsKeys map[string]bool        `json:"exists_keys"`
	ChainLogs  map[string][][2]string `json:"chain_logs"`
}

// GetRuntime 返回运行时配置的只读快照
// m.mu 的 RLock 已持有时可以安全读取 m.runtime
func (m *Manager) GetRuntime() RuntimeSnapshot {
	m.mu.RLock()
	defer m.mu.RUnlock()
	if m.runtime == nil {
		return RuntimeSnapshot{
			Config:     IClashBase{},
			ExistsKeys: map[string]bool{},
			ChainLogs:  map[string][][2]string{},
		}
	}
	// Manager.mu 已持有 RLock，可直接读取 RuntimeConfig 字段
	return RuntimeSnapshot{
		Config:     m.runtime.Config,
		ExistsKeys: m.runtime.ExistsKeys,
		ChainLogs:  m.runtime.ChainLogs,
	}
}

// SetRuntime 更新运行时配置（增强流水线完成后调用）
func (m *Manager) SetRuntime(r *RuntimeConfig) {
	m.mu.Lock()
	defer m.mu.Unlock()
	m.runtime = r
}

// ─────────────────────────────────────────────────────────────────────────────
// 内部辅助
// ─────────────────────────────────────────────────────────────────────────────

// validateClashCore 验证并修正 clash_core 字段
func (m *Manager) validateClashCore(v *IVerge) error {
	if v.ClashCore == nil {
		core := "verge-mihomo"
		v.ClashCore = &core
		return writeYAML(utils.Dirs().VergePath(), v, "# ClashGo Config")
	}
	for _, valid := range ValidClashCores {
		if *v.ClashCore == valid {
			return nil
		}
	}
	utils.Log().Warn("Invalid clash_core, resetting to default",
		zap.String("invalid", *v.ClashCore))
	core := "verge-mihomo"
	v.ClashCore = &core
	return writeYAML(utils.Dirs().VergePath(), v, "# ClashGo Config")
}

// readYAML 从文件读取并反序列化 YAML
func readYAML[T any](path string) (*T, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", path, err)
	}
	var out T
	if err := yaml.Unmarshal(data, &out); err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, err)
	}
	return &out, nil
}

// readYAMLMap 从文件读取 YAML 为 map
func readYAMLMap(path string) (map[string]interface{}, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var out map[string]interface{}
	if err := yaml.Unmarshal(data, &out); err != nil {
		return nil, err
	}
	if out == nil {
		out = make(map[string]interface{})
	}
	return out, nil
}

// writeYAML 将结构体序列化为 YAML 并原子写入文件（带注释前缀）
// 委托给 WriteYAMLAtomic：强制字符串引号（防折行）+ tmp→rename 原子写
func writeYAML(path string, v interface{}, comment string) error {
	return WriteYAMLAtomic(path, v, comment)
}

// LoadVergeRaw 在 Manager 初始化之前快速读取 verge.yaml（用于 app.StartHidden()）
func LoadVergeRaw() (*IVerge, error) {
	return readYAML[IVerge](utils.Dirs().VergePath())
}

// defaultClashBase 返回默认的 Clash 基础配置
func defaultClashBase() IClashBase {
	return IClashBase{
		"mixed-port":          17897,
		"socks-port":          17898,
		"port":                17899,
		"redir-port":          17895,
		"tproxy-port":         17896,
		"log-level":           "info",
		"allow-lan":           false,
		"ipv6":                true,
		"mode":                "rule",
		"external-controller": "127.0.0.1:19097",
		"unified-delay":       true,
		"secret":              "clashgo-secret",
		"tun": map[string]interface{}{
			"enable":                false,
			"stack":                 "system",
			"auto-route":            true,
			"strict-route":          false,
			"auto-detect-interface": true,
			"dns-hijack":            []string{"any:53"},
		},
	}
}

// applyVergePatch 将 patch 中非零字段覆盖到 dst
// 用反射实现会更通用，这里用明确字段 mapping 保证类型安全
func applyVergePatch(dst *IVerge, patch *IVerge) {
	if patch.AppLogLevel != nil {
		dst.AppLogLevel = patch.AppLogLevel
	}
	if patch.Language != nil {
		dst.Language = patch.Language
	}
	if patch.ThemeMode != nil {
		dst.ThemeMode = patch.ThemeMode
	}
	if patch.EnableSystemProxy != nil {
		dst.EnableSystemProxy = patch.EnableSystemProxy
	}
	if patch.EnableTunMode != nil {
		dst.EnableTunMode = patch.EnableTunMode
	}
	if patch.ClashCore != nil {
		dst.ClashCore = patch.ClashCore
	}
	if patch.EnableAutoLaunch != nil {
		dst.EnableAutoLaunch = patch.EnableAutoLaunch
	}
	if patch.EnableSilentStart != nil {
		dst.EnableSilentStart = patch.EnableSilentStart
	}
	if patch.ProxyHost != nil {
		dst.ProxyHost = patch.ProxyHost
	}
	if patch.SystemProxyBypass != nil {
		dst.SystemProxyBypass = patch.SystemProxyBypass
	}
	if patch.UseDefaultBypass != nil {
		dst.UseDefaultBypass = patch.UseDefaultBypass
	}
	if patch.EnableProxyGuard != nil {
		dst.EnableProxyGuard = patch.EnableProxyGuard
	}
	if patch.ProxyGuardDuration != nil {
		dst.ProxyGuardDuration = patch.ProxyGuardDuration
	}
	if patch.VergeMixedPort != nil {
		dst.VergeMixedPort = patch.VergeMixedPort
	}
	if patch.VergeSocksPort != nil {
		dst.VergeSocksPort = patch.VergeSocksPort
	}
	if patch.VergeSocksEnabled != nil {
		dst.VergeSocksEnabled = patch.VergeSocksEnabled
	}
	if patch.VergePort != nil {
		dst.VergePort = patch.VergePort
	}
	if patch.VergeHttpEnabled != nil {
		dst.VergeHttpEnabled = patch.VergeHttpEnabled
	}
	if patch.VergeRedirPort != nil {
		dst.VergeRedirPort = patch.VergeRedirPort
	}
	if patch.VergeRedirEnabled != nil {
		dst.VergeRedirEnabled = patch.VergeRedirEnabled
	}
	if patch.VergeTProxyPort != nil {
		dst.VergeTProxyPort = patch.VergeTProxyPort
	}
	if patch.VergeTProxyEnabled != nil {
		dst.VergeTProxyEnabled = patch.VergeTProxyEnabled
	}
	if patch.Hotkeys != nil {
		dst.Hotkeys = patch.Hotkeys
	}
	if patch.EnableGlobalHotkey != nil {
		dst.EnableGlobalHotkey = patch.EnableGlobalHotkey
	}
	if patch.AutoCloseConnection != nil {
		dst.AutoCloseConnection = patch.AutoCloseConnection
	}
	if patch.AutoCheckUpdate != nil {
		dst.AutoCheckUpdate = patch.AutoCheckUpdate
	}
	if patch.DefaultLatencyTest != nil {
		dst.DefaultLatencyTest = patch.DefaultLatencyTest
	}
	if patch.EnableBuiltinEnhanced != nil {
		dst.EnableBuiltinEnhanced = patch.EnableBuiltinEnhanced
	}
	if patch.AutoLogClean != nil {
		dst.AutoLogClean = patch.AutoLogClean
	}
	if patch.EnableAutoBackupSchedule != nil {
		dst.EnableAutoBackupSchedule = patch.EnableAutoBackupSchedule
	}
	if patch.AutoBackupIntervalHours != nil {
		dst.AutoBackupIntervalHours = patch.AutoBackupIntervalHours
	}
	if patch.WebDAVUrl != nil {
		dst.WebDAVUrl = patch.WebDAVUrl
	}
	if patch.WebDAVUsername != nil {
		dst.WebDAVUsername = patch.WebDAVUsername
	}
	if patch.WebDAVPassword != nil {
		dst.WebDAVPassword = patch.WebDAVPassword
	}
	if patch.ThemeSetting != nil {
		dst.ThemeSetting = patch.ThemeSetting
	}
	if patch.EnableDNSSettings != nil {
		dst.EnableDNSSettings = patch.EnableDNSSettings
	}
	if patch.EnableExternalController != nil {
		dst.EnableExternalController = patch.EnableExternalController
	}
	if patch.HomeCards != nil {
		dst.HomeCards = patch.HomeCards
	}
	if patch.TrayProxyGroupsDisplay != nil {
		dst.TrayProxyGroupsDisplay = patch.TrayProxyGroupsDisplay
	}
	if patch.TrayInlineOutboundModes != nil {
		dst.TrayInlineOutboundModes = patch.TrayInlineOutboundModes
	}
	if patch.CollapseNavbar != nil {
		dst.CollapseNavbar = patch.CollapseNavbar
	}
	if patch.StartPage != nil {
		dst.StartPage = patch.StartPage
	}
	if patch.ProxyLayoutColumn != nil {
		dst.ProxyLayoutColumn = patch.ProxyLayoutColumn
	}
	if patch.ProxyAutoConfig != nil {
		dst.ProxyAutoConfig = patch.ProxyAutoConfig
	}
	if patch.PacFileContent != nil {
		dst.PacFileContent = patch.PacFileContent
	}
	if patch.MenuIcon != nil {
		dst.MenuIcon = patch.MenuIcon
	}
	if patch.SysproxyTrayIcon != nil {
		dst.SysproxyTrayIcon = patch.SysproxyTrayIcon
	}
	if patch.TunTrayIcon != nil {
		dst.TunTrayIcon = patch.TunTrayIcon
	}
	if patch.NoticePosition != nil {
		dst.NoticePosition = patch.NoticePosition
	}
}

// applyProfilePatch 合并 profile patch
func applyProfilePatch(dst *IProfile, patch *IProfile) {
	if patch.Name != nil {
		dst.Name = patch.Name
	}
	if patch.Desc != nil {
		dst.Desc = patch.Desc
	}
	if patch.URL != nil {
		dst.URL = patch.URL
	}
	if patch.Interval != nil {
		dst.Interval = patch.Interval
	}
	if patch.Selected != nil {
		dst.Selected = patch.Selected
	}
	if patch.Option != nil {
		dst.Option = patch.Option
	}
	if patch.CurrentMerge != nil {
		dst.CurrentMerge = patch.CurrentMerge
	}
	if patch.CurrentScript != nil {
		dst.CurrentScript = patch.CurrentScript
	}
	if patch.CurrentRules != nil {
		dst.CurrentRules = patch.CurrentRules
	}
	if patch.CurrentProxies != nil {
		dst.CurrentProxies = patch.CurrentProxies
	}
	if patch.CurrentGroups != nil {
		dst.CurrentGroups = patch.CurrentGroups
	}
}
