// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyIconFile(arg1, arg2) {
  return window['go']['api']['BackupAPI']['CopyIconFile'](arg1, arg2);
}

export function CreateLocalBackup() {
  return window['go']['api']['BackupAPI']['CreateLocalBackup']();
}

export function DeleteLocalBackup(arg1) {
  return window['go']['api']['BackupAPI']['DeleteLocalBackup'](arg1);
}

export function DeleteWebDAVBackup(arg1) {
  return window['go']['api']['BackupAPI']['DeleteWebDAVBackup'](arg1);
}

export function DownloadFromWebDAV(arg1) {
  return window['go']['api']['BackupAPI']['DownloadFromWebDAV'](arg1);
}

export function ExportLocalBackup(arg1, arg2) {
  return window['go']['api']['BackupAPI']['ExportLocalBackup'](arg1, arg2);
}

export function GetBackupList() {
  return window['go']['api']['BackupAPI']['GetBackupList']();
}

export function ImportLocalBackup(arg1) {
  return window['go']['api']['BackupAPI']['ImportLocalBackup'](arg1);
}

export function Init(arg1) {
  return window['go']['api']['BackupAPI']['Init'](arg1);
}

export function ListWebDAVFiles() {
  return window['go']['api']['BackupAPI']['ListWebDAVFiles']();
}

export function RestoreLocalBackup(arg1) {
  return window['go']['api']['BackupAPI']['RestoreLocalBackup'](arg1);
}

export function SaveWebDAVConfig(arg1, arg2, arg3) {
  return window['go']['api']['BackupAPI']['SaveWebDAVConfig'](arg1, arg2, arg3);
}

export function UploadToWebDAV() {
  return window['go']['api']['BackupAPI']['UploadToWebDAV']();
}
