// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backup} from '../models';
import {config} from '../models';

export function CopyIconFile(arg1:string,arg2:string):Promise<void>;

export function CreateLocalBackup():Promise<string>;

export function DeleteLocalBackup(arg1:string):Promise<void>;

export function DeleteWebDAVBackup(arg1:string):Promise<void>;

export function DownloadFromWebDAV(arg1:string):Promise<void>;

export function ExportLocalBackup(arg1:string,arg2:string):Promise<void>;

export function GetBackupList():Promise<Array<backup.BackupInfo>>;

export function ImportLocalBackup(arg1:string):Promise<string>;

export function Init(arg1:config.Manager):Promise<void>;

export function ListWebDAVFiles():Promise<Array<backup.RemoteBackupInfo>>;

export function RestoreLocalBackup(arg1:string):Promise<void>;

export function SaveWebDAVConfig(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UploadToWebDAV():Promise<void>;
