// @ts-check
// Wails generated bindings for api.ConfigAPI
// This file is automatically generated during `wails build` or `wails dev`

'use strict';

import { Call as $Call } from "@wailsio/runtime";

/**
 * GetVergeConfig - 获取 Verge 配置
 */
export function GetVergeConfig() {
    return $Call.ByName("api.ConfigAPI.GetVergeConfig");
}

/**
 * PatchVergeConfig - 更新 Verge 配置
 * @param {Object} patch
 */
export function PatchVergeConfig(patch) {
    return $Call.ByName("api.ConfigAPI.PatchVergeConfig", patch);
}

export function GetClashInfo() {
    return $Call.ByName("api.ConfigAPI.GetClashInfo");
}

export function GetClashConfig() {
    return $Call.ByName("api.ConfigAPI.GetClashConfig");
}

export function PatchClashConfig(payload) {
    return $Call.ByName("api.ConfigAPI.PatchClashConfig", payload);
}

export function PatchClashMode(mode) {
    return $Call.ByName("api.ConfigAPI.PatchClashMode", mode);
}

export function GetRuntimeConfig() {
    return $Call.ByName("api.ConfigAPI.GetRuntimeConfig");
}

export function GetRuntimeYAML() {
    return $Call.ByName("api.ConfigAPI.GetRuntimeYAML");
}

export function GetRuntimeLogs() {
    return $Call.ByName("api.ConfigAPI.GetRuntimeLogs");
}

export function GetRuntimeProxyChainConfig(exitNode) {
    return $Call.ByName("api.ConfigAPI.GetRuntimeProxyChainConfig", exitNode);
}

export function UpdateProxyChainConfigInRuntime(config) {
    return $Call.ByName("api.ConfigAPI.UpdateProxyChainConfigInRuntime", config);
}

export function SaveDNSConfig(data) {
    return $Call.ByName("api.ConfigAPI.SaveDNSConfig", data);
}

export function ApplyDNSConfig(apply) {
    return $Call.ByName("api.ConfigAPI.ApplyDNSConfig", apply);
}

export function CheckDNSConfigExists() {
    return $Call.ByName("api.ConfigAPI.CheckDNSConfigExists");
}

export function GetDNSConfigContent() {
    return $Call.ByName("api.ConfigAPI.GetDNSConfigContent");
}

export function ValidateDNSConfig(content) {
    return $Call.ByName("api.ConfigAPI.ValidateDNSConfig", content);
}

export function UpdateUIStage(stage) {
    return $Call.ByName("api.ConfigAPI.UpdateUIStage", stage);
}

export function GetRuntimeExists() {
    return $Call.ByName("api.ConfigAPI.GetRuntimeExists");
}

export function CopyClashEnv() {
    return $Call.ByName("api.ConfigAPI.CopyClashEnv");
}

export function DownloadIconCache(url, name) {
    return $Call.ByName("api.ConfigAPI.DownloadIconCache", url, name);
}
