// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function ApplyDNSConfig(arg1:boolean):Promise<void>;

export function CheckDNSConfigExists():Promise<boolean>;

export function CopyClashEnv():Promise<string>;

export function DownloadIconCache(arg1:string,arg2:string):Promise<string>;

export function FileExists(arg1:string):Promise<boolean>;

export function GetClashInfo():Promise<config.ClashInfo>;

export function GetDNSConfigContent():Promise<string>;

export function GetRuntimeConfig():Promise<config.RuntimeSnapshot>;

export function GetRuntimeExists():Promise<Array<string>>;

export function GetRuntimeLogs():Promise<Record<string, Array<any>>>;

export function GetRuntimeProxyChainConfig(arg1:string):Promise<string>;

export function GetRuntimeYAML():Promise<string>;

export function GetVergeConfig():Promise<config.IVerge>;

export function GetVergeRaw():Promise<config.IVerge>;

export function Init(arg1:config.Manager):Promise<void>;

export function PatchClashConfig(arg1:Record<string, any>):Promise<void>;

export function PatchClashMode(arg1:string):Promise<void>;

export function PatchVergeConfig(arg1:config.IVerge):Promise<void>;

export function ReadTextFile(arg1:string):Promise<string>;

export function SaveDNSConfig(arg1:Record<string, any>):Promise<void>;

export function UpdateProxyChainConfigInRuntime(arg1:Record<string, any>):Promise<void>;

export function UpdateUIStage(arg1:string):Promise<void>;

export function ValidateDNSConfig():Promise<boolean|string>;

export function WriteTextFile(arg1:string,arg2:string):Promise<void>;
