// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyDNSConfig(arg1) {
  return window['go']['api']['ConfigAPI']['ApplyDNSConfig'](arg1);
}

export function CheckDNSConfigExists() {
  return window['go']['api']['ConfigAPI']['CheckDNSConfigExists']();
}

export function CopyClashEnv() {
  return window['go']['api']['ConfigAPI']['CopyClashEnv']();
}

export function DownloadIconCache(arg1, arg2) {
  return window['go']['api']['ConfigAPI']['DownloadIconCache'](arg1, arg2);
}

export function FileExists(arg1) {
  return window['go']['api']['ConfigAPI']['FileExists'](arg1);
}

export function GetClashInfo() {
  return window['go']['api']['ConfigAPI']['GetClashInfo']();
}

export function GetDNSConfigContent() {
  return window['go']['api']['ConfigAPI']['GetDNSConfigContent']();
}

export function GetRuntimeConfig() {
  return window['go']['api']['ConfigAPI']['GetRuntimeConfig']();
}

export function GetRuntimeExists() {
  return window['go']['api']['ConfigAPI']['GetRuntimeExists']();
}

export function GetRuntimeLogs() {
  return window['go']['api']['ConfigAPI']['GetRuntimeLogs']();
}

export function GetRuntimeProxyChainConfig(arg1) {
  return window['go']['api']['ConfigAPI']['GetRuntimeProxyChainConfig'](arg1);
}

export function GetRuntimeYAML() {
  return window['go']['api']['ConfigAPI']['GetRuntimeYAML']();
}

export function GetVergeConfig() {
  return window['go']['api']['ConfigAPI']['GetVergeConfig']();
}

export function GetVergeRaw() {
  return window['go']['api']['ConfigAPI']['GetVergeRaw']();
}

export function Init(arg1) {
  return window['go']['api']['ConfigAPI']['Init'](arg1);
}

export function PatchClashConfig(arg1) {
  return window['go']['api']['ConfigAPI']['PatchClashConfig'](arg1);
}

export function PatchClashMode(arg1) {
  return window['go']['api']['ConfigAPI']['PatchClashMode'](arg1);
}

export function PatchVergeConfig(arg1) {
  return window['go']['api']['ConfigAPI']['PatchVergeConfig'](arg1);
}

export function ReadTextFile(arg1) {
  return window['go']['api']['ConfigAPI']['ReadTextFile'](arg1);
}

export function SaveDNSConfig(arg1) {
  return window['go']['api']['ConfigAPI']['SaveDNSConfig'](arg1);
}

export function UpdateProxyChainConfigInRuntime(arg1) {
  return window['go']['api']['ConfigAPI']['UpdateProxyChainConfigInRuntime'](arg1);
}

export function UpdateUIStage(arg1) {
  return window['go']['api']['ConfigAPI']['UpdateUIStage'](arg1);
}

export function ValidateDNSConfig() {
  return window['go']['api']['ConfigAPI']['ValidateDNSConfig']();
}

export function WriteTextFile(arg1, arg2) {
  return window['go']['api']['ConfigAPI']['WriteTextFile'](arg1, arg2);
}
