// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckMediaUnlock() {
  return window['go']['api']['MediaUnlockAPI']['CheckMediaUnlock']();
}

export function GetUnlockItems() {
  return window['go']['api']['MediaUnlockAPI']['GetUnlockItems']();
}
