// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {unlock} from '../models';

export function CheckMediaUnlock():Promise<Array<unlock.UnlockItem>>;

export function GetUnlockItems():Promise<Array<unlock.UnlockItem>>;
