// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';
import {config} from '../models';

export function CreateProfile(arg1:api.CreateProfileRequest):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function EnhanceProfiles():Promise<void>;

export function GetNextUpdateTime(arg1:string):Promise<number>;

export function GetProfiles():Promise<config.IProfiles>;

export function ImportProfile(arg1:api.ImportProfileRequest):Promise<void>;

export function Init(arg1:config.Manager):Promise<void>;

export function NotifyValidationResult(arg1:string,arg2:string):Promise<void>;

export function PatchProfile(arg1:string,arg2:config.IProfile):Promise<void>;

export function PatchProfilesConfig(arg1:string):Promise<void>;

export function ReadProfileFile(arg1:string):Promise<string>;

export function ReorderProfile(arg1:string,arg2:string):Promise<void>;

export function SaveProfileFile(arg1:string,arg2:string):Promise<void>;

export function SaveProfileFileWithValidation(arg1:string,arg2:string):Promise<void>;

export function UpdateProfile(arg1:string,arg2:config.ProfileOption):Promise<void>;

export function ValidateScriptFile(arg1:string):Promise<void>;

export function ViewProfileInExplorer(arg1:string):Promise<void>;
