// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProfile(arg1) {
  return window['go']['api']['ProfileAPI']['CreateProfile'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['api']['ProfileAPI']['DeleteProfile'](arg1);
}

export function EnhanceProfiles() {
  return window['go']['api']['ProfileAPI']['EnhanceProfiles']();
}

export function GetNextUpdateTime(arg1) {
  return window['go']['api']['ProfileAPI']['GetNextUpdateTime'](arg1);
}

export function GetProfiles() {
  return window['go']['api']['ProfileAPI']['GetProfiles']();
}

export function ImportProfile(arg1) {
  return window['go']['api']['ProfileAPI']['ImportProfile'](arg1);
}

export function Init(arg1) {
  return window['go']['api']['ProfileAPI']['Init'](arg1);
}

export function NotifyValidationResult(arg1, arg2) {
  return window['go']['api']['ProfileAPI']['NotifyValidationResult'](arg1, arg2);
}

export function PatchProfile(arg1, arg2) {
  return window['go']['api']['ProfileAPI']['PatchProfile'](arg1, arg2);
}

export function PatchProfilesConfig(arg1) {
  return window['go']['api']['ProfileAPI']['PatchProfilesConfig'](arg1);
}

export function ReadProfileFile(arg1) {
  return window['go']['api']['ProfileAPI']['ReadProfileFile'](arg1);
}

export function ReorderProfile(arg1, arg2) {
  return window['go']['api']['ProfileAPI']['ReorderProfile'](arg1, arg2);
}

export function SaveProfileFile(arg1, arg2) {
  return window['go']['api']['ProfileAPI']['SaveProfileFile'](arg1, arg2);
}

export function SaveProfileFileWithValidation(arg1, arg2) {
  return window['go']['api']['ProfileAPI']['SaveProfileFileWithValidation'](arg1, arg2);
}

export function UpdateProfile(arg1, arg2) {
  return window['go']['api']['ProfileAPI']['UpdateProfile'](arg1, arg2);
}

export function ValidateScriptFile(arg1) {
  return window['go']['api']['ProfileAPI']['ValidateScriptFile'](arg1);
}

export function ViewProfileInExplorer(arg1) {
  return window['go']['api']['ProfileAPI']['ViewProfileInExplorer'](arg1);
}
