// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeCoreVersion(arg1) {
  return window['go']['api']['ProxyAPI']['ChangeCoreVersion'](arg1);
}

export function ClearLogs() {
  return window['go']['api']['ProxyAPI']['ClearLogs']();
}

export function DNSQuery(arg1, arg2) {
  return window['go']['api']['ProxyAPI']['DNSQuery'](arg1, arg2);
}

export function DeleteAllConnections() {
  return window['go']['api']['ProxyAPI']['DeleteAllConnections']();
}

export function DeleteConnection(arg1) {
  return window['go']['api']['ProxyAPI']['DeleteConnection'](arg1);
}

export function GetClashLogs() {
  return window['go']['api']['ProxyAPI']['GetClashLogs']();
}

export function GetConnections() {
  return window['go']['api']['ProxyAPI']['GetConnections']();
}

export function GetCoreVersion() {
  return window['go']['api']['ProxyAPI']['GetCoreVersion']();
}

export function GetProviders() {
  return window['go']['api']['ProxyAPI']['GetProviders']();
}

export function GetProxies() {
  return window['go']['api']['ProxyAPI']['GetProxies']();
}

export function GetRules() {
  return window['go']['api']['ProxyAPI']['GetRules']();
}

export function GetTraffic() {
  return window['go']['api']['ProxyAPI']['GetTraffic']();
}

export function Init(arg1) {
  return window['go']['api']['ProxyAPI']['Init'](arg1);
}

export function RestartCore() {
  return window['go']['api']['ProxyAPI']['RestartCore']();
}

export function SelectProxy(arg1, arg2) {
  return window['go']['api']['ProxyAPI']['SelectProxy'](arg1, arg2);
}

export function StartCore() {
  return window['go']['api']['ProxyAPI']['StartCore']();
}

export function StopCore() {
  return window['go']['api']['ProxyAPI']['StopCore']();
}

export function SyncTrayProxySelection() {
  return window['go']['api']['ProxyAPI']['SyncTrayProxySelection']();
}

export function TestDelay(arg1) {
  return window['go']['api']['ProxyAPI']['TestDelay'](arg1);
}

export function TestProxyDelay(arg1, arg2, arg3) {
  return window['go']['api']['ProxyAPI']['TestProxyDelay'](arg1, arg2, arg3);
}

export function UpdateGeoData() {
  return window['go']['api']['ProxyAPI']['UpdateGeoData']();
}

export function UpdateProxyProvider(arg1) {
  return window['go']['api']['ProxyAPI']['UpdateProxyProvider'](arg1);
}
