// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {mihomo} from '../models';
import {config} from '../models';

export function ChangeCoreVersion(arg1:string):Promise<void>;

export function ClearLogs():Promise<void>;

export function DNSQuery(arg1:string,arg2:string):Promise<Array<string>>;

export function DeleteAllConnections():Promise<void>;

export function DeleteConnection(arg1:string):Promise<void>;

export function GetClashLogs():Promise<Array<string>>;

export function GetConnections():Promise<mihomo.ConnectionsResponse>;

export function GetCoreVersion():Promise<string>;

export function GetProviders():Promise<mihomo.ProvidersResponse>;

export function GetProxies():Promise<mihomo.ProxiesResponse>;

export function GetRules():Promise<mihomo.RulesResponse>;

export function GetTraffic():Promise<mihomo.TrafficStats>;

export function Init(arg1:config.Manager):Promise<void>;

export function RestartCore():Promise<void>;

export function SelectProxy(arg1:string,arg2:string):Promise<void>;

export function StartCore():Promise<void>;

export function StopCore():Promise<void>;

export function SyncTrayProxySelection():Promise<string>;

export function TestDelay(arg1:string):Promise<number>;

export function TestProxyDelay(arg1:string,arg2:string,arg3:number):Promise<number>;

export function UpdateGeoData():Promise<void>;

export function UpdateProxyProvider(arg1:string):Promise<void>;
