// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetServiceStatus() {
  return window['go']['api']['ServiceAPI']['GetServiceStatus']();
}

export function Init() {
  return window['go']['api']['ServiceAPI']['Init']();
}

export function InstallService() {
  return window['go']['api']['ServiceAPI']['InstallService']();
}

export function InvokeUWPTool() {
  return window['go']['api']['ServiceAPI']['InvokeUWPTool']();
}

export function IsServiceAvailable() {
  return window['go']['api']['ServiceAPI']['IsServiceAvailable']();
}

export function ReinstallService() {
  return window['go']['api']['ServiceAPI']['ReinstallService']();
}

export function RepairService() {
  return window['go']['api']['ServiceAPI']['RepairService']();
}

export function UninstallService() {
  return window['go']['api']['ServiceAPI']['UninstallService']();
}
