// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';

export function GetServiceStatus():Promise<service.ServiceStatus>;

export function Init():Promise<void>;

export function InstallService():Promise<void>;

export function InvokeUWPTool():Promise<void>;

export function IsServiceAvailable():Promise<boolean>;

export function ReinstallService():Promise<void>;

export function RepairService():Promise<void>;

export function UninstallService():Promise<void>;
