// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {mihomo} from '../models';
import {api} from '../models';
import {proxy} from '../models';

export function CheckPortAvailable(arg1:number):Promise<boolean>;

export function CopyClashEnv():Promise<string>;

export function DeleteAllConnections():Promise<void>;

export function DeleteConnection(arg1:string):Promise<void>;

export function EntryLightweightMode():Promise<string>;

export function ExitLightweightMode():Promise<string>;

export function GetAppDir():Promise<string>;

export function GetAutoLaunchStatus():Promise<boolean>;

export function GetAutoProxy():Promise<Record<string, any>>;

export function GetConnections():Promise<mihomo.ConnectionsResponse>;

export function GetCoreVersion():Promise<string>;

export function GetNetworkInterfaces():Promise<Array<api.NetworkInterface>>;

export function GetPortableFlag():Promise<boolean>;

export function GetSysProxy():Promise<proxy.ProxyInfo>;

export function GetSystemHostname():Promise<string>;

export function GetSystemInfo():Promise<api.SystemInfo>;

export function GetTrafficStats():Promise<Array<api.IOCounter>>;

export function Init():Promise<void>;

export function OpenAppDir():Promise<void>;

export function OpenAppLog():Promise<void>;

export function OpenCoreDir():Promise<void>;

export function OpenCoreLog():Promise<void>;

export function OpenLogsDir():Promise<void>;

export function OpenWebURL(arg1:string):Promise<void>;

export function SetMihomoServer(arg1:string,arg2:string):Promise<void>;

export function SetProxy(arg1:proxy.SysProxy):Promise<void>;

export function ViewProfileFile(arg1:string):Promise<void>;
