// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckPortAvailable(arg1) {
  return window['go']['api']['SystemAPI']['CheckPortAvailable'](arg1);
}

export function CopyClashEnv() {
  return window['go']['api']['SystemAPI']['CopyClashEnv']();
}

export function DeleteAllConnections() {
  return window['go']['api']['SystemAPI']['DeleteAllConnections']();
}

export function DeleteConnection(arg1) {
  return window['go']['api']['SystemAPI']['DeleteConnection'](arg1);
}

export function EntryLightweightMode() {
  return window['go']['api']['SystemAPI']['EntryLightweightMode']();
}

export function ExitLightweightMode() {
  return window['go']['api']['SystemAPI']['ExitLightweightMode']();
}

export function GetAppDir() {
  return window['go']['api']['SystemAPI']['GetAppDir']();
}

export function GetAutoLaunchStatus() {
  return window['go']['api']['SystemAPI']['GetAutoLaunchStatus']();
}

export function GetAutoProxy() {
  return window['go']['api']['SystemAPI']['GetAutoProxy']();
}

export function GetConnections() {
  return window['go']['api']['SystemAPI']['GetConnections']();
}

export function GetCoreVersion() {
  return window['go']['api']['SystemAPI']['GetCoreVersion']();
}

export function GetNetworkInterfaces() {
  return window['go']['api']['SystemAPI']['GetNetworkInterfaces']();
}

export function GetPortableFlag() {
  return window['go']['api']['SystemAPI']['GetPortableFlag']();
}

export function GetSysProxy() {
  return window['go']['api']['SystemAPI']['GetSysProxy']();
}

export function GetSystemHostname() {
  return window['go']['api']['SystemAPI']['GetSystemHostname']();
}

export function GetSystemInfo() {
  return window['go']['api']['SystemAPI']['GetSystemInfo']();
}

export function GetTrafficStats() {
  return window['go']['api']['SystemAPI']['GetTrafficStats']();
}

export function Init() {
  return window['go']['api']['SystemAPI']['Init']();
}

export function OpenAppDir() {
  return window['go']['api']['SystemAPI']['OpenAppDir']();
}

export function OpenAppLog() {
  return window['go']['api']['SystemAPI']['OpenAppLog']();
}

export function OpenCoreDir() {
  return window['go']['api']['SystemAPI']['OpenCoreDir']();
}

export function OpenCoreLog() {
  return window['go']['api']['SystemAPI']['OpenCoreLog']();
}

export function OpenLogsDir() {
  return window['go']['api']['SystemAPI']['OpenLogsDir']();
}

export function OpenWebURL(arg1) {
  return window['go']['api']['SystemAPI']['OpenWebURL'](arg1);
}

export function SetMihomoServer(arg1, arg2) {
  return window['go']['api']['SystemAPI']['SetMihomoServer'](arg1, arg2);
}

export function SetProxy(arg1) {
  return window['go']['api']['SystemAPI']['SetProxy'](arg1);
}

export function ViewProfileFile(arg1) {
  return window['go']['api']['SystemAPI']['ViewProfileFile'](arg1);
}
