// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Bindings() {
  return window['go']['main']['App']['Bindings']();
}

export function EntryLightweightMode() {
  return window['go']['main']['App']['EntryLightweightMode']();
}

export function ExitApp() {
  return window['go']['main']['App']['ExitApp']();
}

export function ExitLightweightMode() {
  return window['go']['main']['App']['ExitLightweightMode']();
}

export function ExportDiagnosticInfo() {
  return window['go']['main']['App']['ExportDiagnosticInfo']();
}

export function GetAppUptime() {
  return window['go']['main']['App']['GetAppUptime']();
}

export function GetRunningMode() {
  return window['go']['main']['App']['GetRunningMode']();
}

export function IsAdmin() {
  return window['go']['main']['App']['IsAdmin']();
}

export function IsLightweightMode() {
  return window['go']['main']['App']['IsLightweightMode']();
}

export function NotifyUIReady() {
  return window['go']['main']['App']['NotifyUIReady']();
}

export function OpenDevtools() {
  return window['go']['main']['App']['OpenDevtools']();
}

export function RestartApp() {
  return window['go']['main']['App']['RestartApp']();
}

export function StartHidden() {
  return window['go']['main']['App']['StartHidden']();
}

export function SyncTrayProxySelection() {
  return window['go']['main']['App']['SyncTrayProxySelection']();
}
