// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Bindings():Promise<Array<any>>;

export function EntryLightweightMode():Promise<void>;

export function ExitApp():Promise<void>;

export function ExitLightweightMode():Promise<void>;

export function ExportDiagnosticInfo():Promise<string>;

export function GetAppUptime():Promise<number>;

export function GetRunningMode():Promise<string>;

export function IsAdmin():Promise<boolean>;

export function IsLightweightMode():Promise<boolean>;

export function NotifyUIReady():Promise<void>;

export function OpenDevtools():Promise<void>;

export function RestartApp():Promise<void>;

export function StartHidden():Promise<boolean>;

export function SyncTrayProxySelection():Promise<void>;
